// ui/src/app/movie-details/movie-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Movie } from 'src/app/medias.model';
import { MediaService } from '../media.service';

@Component({
  selector: 'app-movie-details',
  templateUrl: './movie-details.component.html',
  styleUrls: ['./movie-details.component.css'],
})
export class MovieDetailsComponent implements OnInit {
  movie!: Movie | undefined;

  constructor(
    private route: ActivatedRoute,
    private mediaService: MediaService
  ) {}

  ngOnInit(): void {
    const { movieId } = this.route.snapshot.params;
    this.mediaService.getMovieById(movieId).subscribe((data) => {
      this.movie = data;
    });
  }
}

<div *ngIf="movie">
  <h1>{{ movie.title }}</h1>
  <div class="component-container">
    <img [src]="movie.posterUrl" alt="poster" />
    <div class="details-container">
      <p>Director(s): {{ movie.directors.join(", ") }}</p>
      <p>Play time: {{ movie.length }}</p>
      <p>Released in {{ movie.year }}</p>
      <p>{{ movie.watched ? "Already seen" : "Not seen yet" }}</p>
    </div>
  </div>
</div>

// ui_react/src/Pages/MovieDetails.tsx
import { useLoaderData } from "react-router-dom";
import { MovieType } from "../types";

const MovieDetails = () => {
  const movie = useLoaderData() as MovieType;
  return (
    <div>
      <img src={movie.posterUrl} alt="movie poster" />
      <div>
        <h2>{movie.title}</h2>
        <p>Director(s): {movie.directors.join(", ")}</p>
        <p>Play time: {movie.length}</p>
        <p>Released in {movie.year}</p>
      </div>
    </div>
  );
};

export default MovieDetails;
