// ui_react/src/Pages/SeriesDetails.tsx
import { useLoaderData } from "react-router-dom";
import { SeriesType } from "../types";

const SeriesDetails = () => {
  const series = useLoaderData() as SeriesType;
  return (
    <div>
      <img src={series.posterUrl} alt="TV show poster" />
      <div>
        <h2>{series.title}</h2>
        <p>Creator(s): {series.directors.join(", ")}</p>
        <p>Episodes: {series.episodes}</p>
        <p>Seasons: {series.seasons}</p>
        <p>Average play time per episode: {series.length}</p>
        <p>
          Played between {series.startYear} - {series.endYear}
        </p>
      </div>
    </div>
  );
};

export default SeriesDetails;

// ui/src/app/series-details/series-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Media } from 'src/assets/movies';
import { series } from 'src/assets/series';

@Component({
  selector: 'app-series-details',
  templateUrl: './series-details.component.html',
  styleUrls: ['./series-details.component.css'],
})
export class SeriesDetailsComponent implements OnInit {
  series!: Media | undefined;

  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    const { seriesId } = this.route.snapshot.params;
    this.series = series.find((series) => series.id === Number(seriesId));
  }
}

<div *ngIf="series">
  <h1>{{ series.title }}</h1>
  <div class="component-container">
    <img [src]="series.poster" alt="poster" />
    <div class="details-container">
      <p>Creator(s): {{ series.directors.join(", ") }}</p>
      <p>Episodes: {{ series.episodes }}</p>
      <p>Seasones: {{ series.seasons }}</p>
      <p>Average play time per episode: {{ series.length }}</p>
      <p>Played between {{ series.year }}</p>
      <p>{{ series.watched ? "Already seen" : "Not seen yet" }}</p>
    </div>
  </div>
</div>
